train:
  input_width: 672
  label_width: 96
  shift: 96
  epochs: 20
  learning_rate: 0.001
  sequence_stride: 1
model:
  nn_model_type: 'ctxt_conv_rnn'
  conv_width: 5
  lstm_units: 512
  out_steps: 96
  dropout: 0.1
