train:
  input_width: 672
  label_width: 96
  shift: 96
  epochs: 0
  learning_rate: 0.001
  sequence_stride: 96
model:
  nn_model_type: 'xgboost'
  estimators: 25
  max_depth: 4
  early_stopping_rounds: 10
  subsample: 1
  regularization: 1